[build]
  command = "npm run build"
  publish = "dist/public"
  functions = "netlify/functions"

# Direct API requests to Netlify functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Direct all frontend React routes (Wouter) to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
